version: "3.8"

services:

  jmeter-master:
    image: justb4/jmeter
    environment:
      - JVM_XMS=512
      - JVM_XMX=1024
      - JMETER_REMOTE_HOSTS=jmeter-slave-1,jmeter-slave-2,jmeter-slave-3
    volumes:
      - ../tests:/tests
    depends_on:
      - jmeter-slave-1
      - jmeter-slave-2
      - jmeter-slave-3
    entrypoint: ["sh", "-c"]
    command: ["while true; do sleep 30; done"]
   
  jmeter-slave-1:
    image: justb4/jmeter
    environment:
      - JVM_XMS=512
      - JVM_XMX=1024 
      - JVM_ARGS=-Dserver.rmi.ssl.disable=true -Dserver.rmi.port=1099
    command: >
      jmeter-server
      -Dserver.rmi.ssl.disable=true
      
     
  jmeter-slave-2:
    image: justb4/jmeter
    environment:
      - JVM_XMS=512
      - JVM_XMX=1024
      - JVM_ARGS=-Dserver.rmi.ssl.disable=true -Dserver.rmi.port=1099
    command: >
      jmeter-server
      -Dserver.rmi.ssl.disable=true
      
       
  jmeter-slave-3:
    image: justb4/jmeter
    environment:
      - JVM_XMS=512
      - JVM_XMX=1024
      - JVM_ARGS=-Dserver.rmi.ssl.disable=true -Dserver.rmi.port=1099
    command: >
      jmeter-server
      -Dserver.rmi.ssl.disable=true
      
   