version: "3.8"

services:

  jmeter-master:
    image: justb4/jmeter
    container_name: jmeter-master
    environment:
      - JVM_XMS=512m
      - JVM_XMX=1024m
    volumes:
      - ./tests:/tests
    depends_on:
      - jmeter-slave-1
      - jmeter-slave-2
      - jmeter-slave-3
    entrypoint: ["sh", "-c"]
    command: "tail -f /dev/null"

  jmeter-slave-1:
    image: justb4/jmeter
    container_name: jmeter-slave-1
    environment:
      - JVM_XMS=512m
      - JVM_XMX=1024m 
    command: jmeter-server

  jmeter-slave-2:
    image: justb4/jmeter
    container_name: jmeter-slave-2
    environment:
      - JVM_XMS=512m
      - JVM_XMX=1024m
    command: jmeter-server

  jmeter-slave-3:
    image: justb4/jmeter
    container_name: jmeter-slave-3
    environment:
      - JVM_XMS=512m
      - JVM_XMX=1024m
    command: jmeter-server

