name: Distributed Testing using Docker

on:
  push:
    branches:
      - master

jobs:
  Distributed-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restart Cotainers
        run: | 
          docker compose -f docker/docker-compose.yml down -v --remove-orphans
          docker network prune -f
          docker compose -f docker/docker-compose.yml up -d --force-recreate
          docker ps -a

      - name: Test DNS
        run: docker compose -f docker/docker-compose.yml exec jmeter-master ping -c 2 jmeter-slave-1

      - name: Get slave IPs
        run: |
          IP1=$(docker compose -f docker/docker-compose.yml exec -T jmeter-master getent hosts jmeter-slave-1 | awk '{print $1}')
          IP2=$(docker compose -f docker/docker-compose.yml exec -T jmeter-master getent hosts jmeter-slave-2 | awk '{print $1}')
          IP3=$(docker compose -f docker/docker-compose.yml exec -T jmeter-master getent hosts jmeter-slave-3 | awk '{print $1}')

          echo "IPS=$IP1,$IP2,$IP3" >> $GITHUB_ENV

      - name: Check Container Logs
        run: docker compose -f docker/docker-compose.yml logs
      
      - name: Wait
        run: sleep 10

      - name: check jmeter-master is up and running
        run: docker compose -f docker/docker-compose.yml logs jmeter-master

      - name: Verify repo files
        run: |
          ls -R

      - name: Check inside container
        run: docker compose -f docker/docker-compose.yml exec jmeter-master ls -l /tests

      - name: run load test
        run: | 
          docker compose -f docker/docker-compose.yml exec jmeter-master jmeter -Dserver.rmi.ssl.disable=true -n -t /tests/Petstore.jmx -R jmeter-slave-1,jmeter-slave-2,jmeter-slave-3 -l results.jtl -e -o report -JThread=5 -JRampup=2 -JDuration=300 -JSLA=15000

      - name: upload report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter report
          path: | 
            results.jtl
            report/

      - name: Cleanup
        run: docker compose -f docker/docker-compose.yml down
