name: Distributed Testing using Docker

on:
  push:
    branches:
      - master

jobs:
  Distributed-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Spin up Machine
        run: | 
          docker compose -f docker/docker-compose.yml up -d
          docker ps -a

      - name: Check Container Logs
        run: docker compose -f docker/docker-compose.yml logs
      
      - name: Wait
        run: sleep 10

      - name: check jmeter-master is up and running
        run: docker logs jmeter-master

      - name: run load test
        run: | 
          docker exec jmeter-master bash -c 'export JVM_ARGS="-Xms512m -Xmx1024m"; jmeter -n -t /tests/Petstore.jmx -R jmeter-slave-1,jmeter-slave-2,jmeter-slave-3 -l /tests/results.jtl -e -o /tests/report -JThread=5 -JRampup=2 -JDuration=300 -JSLA=15000'

      - name: upload report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter report
          path: tests/report

      - name: Cleanup
        run: docker compose -f docker/docker-compose.yml down
